[package]
name = "marieSerenity"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
serenity = "0.12"
poise = "0.6.1"
dotenv = "0.15.0"
env_logger = "0.11.3"
